apiVersion: apps/v1
kind: Deployment
metadata: 
  name: py-app
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: py-one
  template:
    metadata:
      labels:
        app: py-one
    spec:
      containers:
      - name: py-one
        image: hubtet.azurecr.io/py/pyhello:v1
        ports:
        - containerPort: 5000
        # env:
        #   - name: TITLE
        #     value: "Welcome to Azure Kubernetes Service (AKS)"

# ---
# apiVersion: v1
# kind: Service
# metadata: 
#   name: py-app
# spec:
#   type: ClusterIP
#   ports:
#   - port: 80
#   selector:
#     app: hw-one



