
name: docker_build_push_acr
on:
  workflow_dispatch:
  path:
    branch: [ "main" ]
env:
  IMAGE_NAME: pyhello
  TAG: v2
jobs:
  docker_build_push_acr:
    name: 'docker_build_push_acr'
    runs on: [self-hosted, Linux, X64, custrunner]

    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # with:
      #   ref: main
      #   submodules: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        endpoint: builders

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:    
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the frontend image and push it to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} #tamopsgithubacr.azurecr.io/aspcoresample:${{ github.sha }}
        file: hello/Dockerfile
        #${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
